### ISSUE TITLE
在运行nb run时出现以下报错

### ISSUE THREAD

**Issue by beiyaoo** [lgc2333/ShigureBot#5]
之前步骤都按README.md正常安装 但到nb run出现以下报错
`C:\Users\Administrator\Desktop\ShigureBot-main\ShigureBot-main>nb run
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\__main__.py", line 7, in main
    anyio.run(cli_main, *args)
  File "C:\Program Files\Python310\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Program Files\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Program Files\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\cli\utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "C:\Program Files\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Program Files\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Program Files\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\cli\utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "C:\Program Files\Python310\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Program Files\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\cli\commands\project.py", line 353, in run
    proc = await run_project(
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\handlers\meta.py", line 110, in wrapper
    return await func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\nb_cli\handlers\meta.py", line 155, in wrapper
    raise NoneBotNotInstalledError(_("NoneBot is not installed."))
nb_cli.exceptions.NoneBotNotInstalledError: NoneBot 未安装.

C:\Users\Administrator\Desktop\ShigureBot-main\ShigureBot-main>python bot.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ShigureBot-main\ShigureBot-main\bot.py", line 4, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'

`C:\Users\Administrator\Desktop\ShigureBot-main\ShigureBot-main>``

**Comment by lgc2333** [comment]
没装依赖

**Comment by lgc2333** [comment]
关于bot的安装和配置欢迎来群聊1105946125讨论，这边不好详谈
还有我写的这玩意写成了一堆屎山，一直想重构但是懒了，凑合用吧
